### PR TITLE
Add a --msg argument to opam-publish submit

### LINKED ISSUE #8: add the list of changes to the PR
This is kind of a complex feature request, but that would be great if we could have the list of changes displayed in the description of the PR. A possible idea on how to do that:

- look at the root of the archive for `CHANGES`, `CHANGES.txt` or `CHANGES.md`
- diff the file with the previous released version
- add the new entries in the PR description

### PR DESCRIPTION
**Pull request by samoht**
Fix #8 

Note: the patch applies cleanly to 0.3.1 and master. I'd be great to make a 0.3.2 release with that patch so it can be used by the upcoming `topkg` release. Thanks!

### CODE REVIEW

**Comment by samoht** [comment]
@AltGr ping?

**Comment by AltGr** [comment]
Thanks!

**Comment by dbuenzli** [comment]
Would it be possible to get a release with Thomas' addition ? I'd like to fix https://github.com/dbuenzli/topkg/issues/36 for the next topkg release.

**Pull request merged**
